print("mera name hi shinchan hai")
print("me shararat se bhara")
print("badi mushkil me padi meri family nohara")
print("come on baby come on baby aao kare dance shuru")
print("masti se jhume hum tum ghoome naacho naacho")
print("Dekho sab ko hila duu")
print("shinchan pyara")
print("shinchan shinchan pyara pyara shinchan shinchan pyara")
print("tang kare hai itna q")